### ISSUE TITLE
403 after save user with yubikey

### ISSUE THREAD

**Issue by innertruth** [akeeba/yubikeyauth#1]
I'm trying to get my Yubikey working. I follow the steps, the code appears in the appropriate field. After I click Save I get: 403 Access Denied. I asked my provider if curl is present and access 443 to the yubico authentication servers is open. They confirm that both prereqs are met.
In the apache error log I see nothing. I use Admin Tools, and have changed some settings on/off, and tried again with each change, but to no avail, still getting 403.
How can I see what's causing the 403 error?

**Comment by innertruth** [comment]
A remark, I disabled AdminTools temporarily with this: https://www.akeebabackup.com/documentation/troubleshooter/atwafissues.html
Then I used my Yubikey to enable two factor for my super user in Joomla and this time it worked. I logged out and could log in with two factor yubi. Then I enabled AdminTools again. Logged out and I can still log in with two factor.
It seems that there's some setting in AdminTools I could toggle to get it enabled too, but I don't know which one. Anyway, disabling AdminTools temporarily works too.

**Comment by nikosdion** [comment]
That's because you had enabled the "Disable editing backend users' properties" feature in Admin Tools. Please read the documentation. As you can see it did exactly what you asked it to do.

**Comment by innertruth** [comment]
I was sure I toggled this parameter, but maybe I didn't save it after toggling. My bad. Thanks for the response.

**Comment by nikosdion** [comment]
No problem :)
